### PR TITLE
Add support for the timescaledb extension.

### PR DESCRIPTION
**Pull request by dimitri**
This extension requires specific pre and post pg_restore steps to be implemented, and also seems to require pgcopydb to use a superuser role to be able to fetch the data and use pg_dump.

### CODE REVIEW

**Comment by arajkumar** [comment]
@dimitri Do you think this could be merged to the main?

**Comment by dimitri** [comment]
> @dimitri Do you think this could be merged to the main?

Yeah, if tested and proven to work, which is where we stopped internally. Apparently what we do here isn't always enough for timescaledb to be happy with the migration. Could you test this PR in production? Did it work ok for you?

**Comment by arajkumar** [comment]
So far we have been evaluating pg_dump/pg_restore to (1)migrate schema (2)initial data and 3) `pgcopydb follow` with some custom changes(child table to parent mapping) for live message replication. I will test pgcopydb for (1), and (2) and share my feedback.

**Comment by shusaan** [comment]
any ETA on this please
@dimitri @arajkumar

**Comment by dimitri** [comment]
Hi @shusaan ; no ETA is ever going to be published on this project. I hope you understand what is Open Source and that this project is actually an Open Source project. You get all our work for free, and we welcome you to contribrute to the project, and as a result the only way for you have an ETA on any development (including bug fixes) is to contribute the development yourself.

How are you willing to contribute to pgcopydb?

**Comment by shusaan** [comment]
> Hi @shusaan ; no ETA is ever going to be published on this project. I hope you understand what is Open Source and that this project is actually an Open Source project. You get all our work for free, and we welcome you to contribrute to the project, and as a result the only way for you have an ETA on any development (including bug fixes) is to contribute the development yourself.
> 
> How are you willing to contribute to pgcopydb?

got it,thank you

**Comment by arajkumar** [comment]
@dimitri Let's close this.

It has been accomplished by https://github.com/dimitri/pgcopydb/pull/849

**Pull request closed without merging**
